export const debateTopics = [
    "All students should have daily chores.",
    "Every home should have a pet.",
    "Every student should be required to play a musical instrument.",
    "Homework should be banned.",
    "School uniforms should be required.",
    "Year-round education is better for students.",
    "Children should not be allowed to drink soda.",
    "Gym should be required of all students throughout middle and high school.",
    "All students should be required to volunteer in the community.",
    "Corporal punishment should be allowed in schools.",
    "The internet should be banned from schools.",
    "Junk food should be banned from schools.",
    "All museums should be free to the public.",
    "Students should be held legally responsible for bullying in schools.",
    "Children under 14 should not be allowed on social media sites.",
    "Statewide tests should be abolished.",
    "Everyone should be vegetarians.",
    "Zoos should be abolished.",
    "It is sometimes right for the government to restrict freedom of speech.",
    "Androids are better than iPhones.",
    "The moon should be colonized.",
    "Mixed Martial Arts (MMA) should be banned.",
    "All students should be required to take a cooking class.",
    "All students should be required to take a shop or practical arts class.",
    "All students should be required to take a performing arts class.",
    "All students should be required to learn sewing.",
    "Democracy is the best form of government.",
    "America should have a king and not a president.",
    "All citizens should be required to vote.",
    "The death penalty is an appropriate penalty for certain crimes.",
    "Professional athletes are paid too much money.",
    "Students should never be forced to repeat a year at school.",
    "Grades should be abolished.",
    "All individuals should pay the same tax rate.",
    "Teachers should be replaced by computers.",
    "Students should be allowed to skip grades in school.",
    "The voting age should be lowered.",
    "Video games are too violent.",
    "History is an important subject in school.",
    "Students should not be required to show their work in math.",
    "Every home should have a robot.",
    "The government should provide wireless service for everyone.",
    "Recycling should be required.",
    "Children should not watch television on school nights.",
    "Performance-enhancing drugs should be allowed in sports.",
    "Smartphones should be allowed in classrooms.",
    "School days should start later.",
    "Cursive writing should still be taught in schools.",
    "Competitive sports should be removed from schools.",
    "Art and music classes are as important as math and science.",
    "Students should have a say in hiring new teachers.",
    "Standardized testing is an accurate measure of student ability.",
    "Schools should provide free lunches for all students.",
    "Recess should be mandatory in all schools.",
    "Schools should have a four-day week instead of five.",
    "All students should learn computer programming.",
    "School libraries should be replaced by digital resources.",
    "Participation trophies should be given in all competitions.",
    "All schools should have a garden that students help maintain.",
    "Students should be allowed to grade their teachers.",
    "All students should learn first aid and CPR.",
    "All schools should have a mandatory nap time.",
    "All students should learn sign language.",
    "Schools should have mandatory meditation or mindfulness sessions.",
    "Schools should have dress codes for teachers.",
    "Students should be allowed to choose their own classes.",
    "All schools should have a student council with real decision-making power.",
    "All students should learn basic car maintenance.",
    "Students should be allowed to use calculators in all math classes.",
    "Schools should have longer summer breaks.",
    "Schools should teach handwriting and typing with equal emphasis.",
    "All schools should have a therapy dog.",
    "Students should be allowed to listen to music during independent work time.",
    "Schools should ban homework on weekends.",
    "Schools should have mandatory 'life skills' classes.",
    "Students should be allowed to choose their own seating arrangements.",
    "Schools should have mandatory nutrition classes.",
    "All students should learn basic woodworking or metalworking.",
    "Students should be allowed to retake tests to improve their grades.",
    "Schools should have mandatory community service requirements.",
    "All schools should have a student-run snack shop or cafe.",
]