export const predefinedOptions = {
  name: [],
  subject: ['Math', 'English', 'Science', 'Social Studies'],
  setting: [
    'In-Class Resource Center', 
    'secondary special class setting', 
    'Pull-Out Resource Center', 
    'Self-Contained Classroom', 
    'General Education'
  ],
  workStyle: [
    'works diligently but struggles with some of the concepts taught in class',
    'works independently and completes assignments thoroughly',
    'requires frequent redirection to stay on task',
    'works diligently and rarely struggles with the concepts taught in class',
    'benefits from sitting next to students who can provide assistance',
    'appears to like the challenge of harder math problems and does not become discouraged when making mistakes',
    'relies heavily on teacher support and intervention to complete work',
    'works well with partners but struggles independently',
    'seeks support independently when needed',
    'quick to begin work but may get stuck on questions',
    'demonstrates creativity but often draws instead of working',
    'works diligently but prefers individual teacher conversations'
  ],
  helpseeking: [
    'will ask for help when they do not understand a question',
    'is hesitant to ask for help even when struggling',
    'prefers to ask questions one-on-one than in front of the class',
    'seeks out a teacher to ask questions when needed',
    'will often stop working if the teacher walks away to assist another student',
    'prefers to work alone and rarely seeks assistance',
    'will ask for help when confused but may become frustrated',
    'frequently states needing help but struggles to identify specific needs',
    'will ask for help when needed without becoming frustrated',
    'benefits from having text read aloud',
    'actively seeks teacher assistance when confused',
    'rarely seeks help independently'
  ],
  personality: [
    'has a great sense of humor and maintains positive relationships with staff and students alike',
    'is quiet but thoughtful and contributes meaningfully when called upon',
    'pays attention during instruction and likes to be a part of discussion, often volunteering answers when the class is asked',
    'is a hard worker and rarely finds themselves distracted during class instruction',
    'is respectful and cooperative when working with peers and teachers',
    'demonstrates the ability to follow guiding questions and prompts when working one-on-one',
    'quiet but friendly, rarely gets distracted by peers',
    'demonstrates growing self-advocacy skills',
    'maintains positive attitude even when facing difficulties',
    'very social and gets along well with peers',
    'demonstrates strong work ethic and self-advocacy',
    'quiet but attentive during instruction',
    'quiet but shows understanding when focused'
  ],
  distractibility: [
    'at times is easily distracted',
    'rarely finds themselves distracted during class instruction',
    'occasionally becomes distracted by peers',
    'is generally able to maintain focus during instruction',
    'disengages during instruction by putting head down and not actively participating',
    'rarely distracted when focused',
    'frequently becomes distracted by peers',
    'occasionally becomes distracted by social interactions',
    'frequently becomes distracted by drawing',
    'easily distracted by social interactions'
  ],
  redirection: [
    'will return to the task at hand and put forth their best effort',
    'responds well to gentle reminders to stay on task',
    'may require multiple prompts to refocus on assigned tasks',
    'typically needs minimal redirection to return to tasks',
    'prefers to wait for teacher guidance and support rather than starting independently',
    'responds well to structured approaches',
    'quickly returns to task when redirected',
    'returns to task with prompting',
    'responds well to teacher check-ins',
    'responds well to quiet check-ins'
  ],
  focusBehavior: [
    'maintains focus, asks questions, and puts forth their best effort',
    'becomes overwhelmed and may shut down when concepts are challenging',
    'analyzes problems for mistakes, learns from them, and actively works to improve',
    'seeks additional examples and clarification until understanding is achieved',
    'determination is evident as they maintain focus, ask questions, and put forth their best effort',
    'faces challenges in initiating work and maintaining engagement',
    'maintains focus and completes work efficiently',
    'maintains focus when given clear structure',
    'maintains focus and asks questions appropriately',
    'needs frequent check-ins to maintain focus',
    'maintains focus with periodic check-ins',
    'maintains focus with regular check-ins',
    'needs frequent quiet reminders to stay on task',
    'maintains focus with individual attention'
  ],
  assessments: [
    'taking modified assessments',
    'small group administration of tests and quizzes',
    'taking modified assessments and small group administration of classroom tests and quizzes',
    'extended time on assessments',
    'small group administration of tests and quizzes and modified assessments',
    'oral assessment options when appropriate',
    'shortened assessments',
    'use of a calculator during assessments',
    'simplified language on written assessments'
  ],
  classPresence: [
    'a pleasure to have in class',
    'a positive influence on classroom dynamics',
    'making progress toward more consistent classroom participation',
    'a valued member of our classroom community',
    'developing stronger self-regulation skills in the classroom',
    'requires significant teacher support to maintain engagement'
  ],
  strengths: [
    'following directions',
    'asking questions without being prompted',
    'classwork completion',
    'work ethic',
    'determination',
    'self-advocacy',
    'teamwork',
    'analyzing problems for mistakes',
    'persistence',
    'following guided questions',
    'working one-on-one',
    'using visual aids',
    'following procedures',
    'independent work',
    'organization',
    'following rules',
    'group work',
    'creativity',
    'understanding when focused',
    'social skills'
  ],
  supports: [
    'study guides',
    'calculators',
    'work examples',
    'retest',
    'additional time for the completion of the assessment',
    'small group instruction',
    'preferential seating',
    'chunked assignments',
    'visual aids',
    'frequent teacher check-ins',
    'modified assignments',
    'one-on-one instruction',
    'clear instructions',
    'structured approaches',
    'individual teacher time'
  ]
} 